In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("C:/Users/91758/Downloads/Recommend.csv",names=['user_id','movie_id','rating','timestamp'])

In [3]:
df.head()

user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
user_id      100000 non-null int64
movie_id     100000 non-null int64
rating       100000 non-null int64
timestamp    100000 non-null int64
dtypes: int64(4)
memory usage: 3.1 MB


In [5]:
df.user_id.nunique()

943

In [6]:
df.movie_id.nunique()

1682

In [11]:
#a=df.groupby(['user_id','movie_id'])

AttributeError: Cannot access callable attribute 'unstack' of 'DataFrameGroupBy' objects, try using the 'apply' method

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
train_data,test_data= train_test_split(df,test_size= 0.25)

In [14]:
train_data

user_id  movie_id  rating  timestamp
51075      224       321       2  888082134
11063      210       243       2  887734998
76473      152       393       5  884018430
46491      568       462       4  877907236
72824      690       240       1  881179469
9136       354       208       4  891217394
26221      292       482       5  881103606
79845      756       195       3  874828967
36587      338       427       4  879438419
10523      262       929       3  879791031
79         127       229       5  884364867
52936      804        11       4  879442954
36232       23        79       4  874785957
95142       41       205       4  890687353
15524      295       389       4  879518298
50265      551      1047       4  892785264
47583      380       443       4  885480283
37168      385       719       2  879447136
57004      442      1188       3  883390609
79407      142        42       4  888640489
80695        7       144       5  891351201
41874      203       258       3  880433368
3497       148       172       5  877016513
15206      401       284       3  891032453
87382      351       258       5  879481386
62986      510       322       3  887667752
55873      615        13       4  879449184
17874      234       427       4  892078386
16981      243       194       4  879988913
59983      861       294       3  881274504
...        ...       ...     ...        ...
97720      711       365       3  879995850
59818      650       509       3  891372233
91816      648       364       5  884882528
3220       279        88       1  882146554
79938       97       193       4  884238997
14554       21       326       5  874950889
5608       269       482       3  891448823
91179      539        56       2  879788046
26562      205       315       4  888284245
83366      889        13       4  880177179
78958      875       511       5  876465188
2340       195       265       4  888737346
7925       105       258       5  889214306
92346      783       895       4  884326787
78118      758       536       2  880672747
43111      585       510       5  891284016
19020      385       942       2  879446208
34937      269       660       1  891448220
43423       45       257       5  881008781
74573      451       302       3  879012647
93353      551       399       3  892785364
28106      511       271       5  890004879
26252      184       512       4  889908716
4329       271       241       3  885849207
99224      304       274       4  884968415
67159       73       894       1  888625592
39055      265       327       3  875320052
8789        42        28       5  881108187
78485      592        96       5  882956241
73484      624       845       3  879793129

[75000 rows x 4 columns]

In [15]:
test_data.shape

(25000, 4)

In [16]:
import numpy as np

In [21]:
n_users=df.user_id.nunique()

In [22]:
n_movies=df.movie_id.nunique()

In [23]:
train_data_matrix= np.zeros((n_users,n_movies))

In [24]:
train_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
for line in train_data.itertuples():
    print(line)
    print(line[1]) #user_id
    print(line[2]) #movie_id
    print(line[3])  #rating
    break

Pandas(Index=51075, user_id=224, movie_id=321, rating=2, timestamp=888082134)
224
321
2


In [28]:
min(df.user_id.unique())

1

In [29]:
max(df.user_id.unique())

943

In [30]:
min(df.movie_id.unique())

1

In [31]:
max(df.movie_id.unique())

1682

In [32]:
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1]=line[3]
    

In [34]:
train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
from sklearn.metrics.pairwise import pairwise_distances

In [36]:
user_similarity= pairwise_distances(train_data_matrix,metric='cosine')

In [37]:
user_similarity.shape

(943, 943)

In [38]:
movie_similarity= pairwise_distances(train_data_matrix.T,metric='cosine')

In [39]:
movie_similarity.shape

(1682, 1682)

In [40]:
movie_similarity

array([[0.        , 0.70037561, 0.78506514, ..., 1.        , 0.94589652,
        0.94589652],
       [0.70037561, 0.        , 0.72336962, ..., 1.        , 0.90560248,
        0.90560248],
       [0.78506514, 0.72336962, 0.        , ..., 1.        , 1.        ,
        0.87617675],
       ...,
       [1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        1.        ],
       [0.94589652, 0.90560248, 1.        , ..., 1.        , 0.        ,
        1.        ],
       [0.94589652, 0.90560248, 0.87617675, ..., 1.        , 1.        ,
        0.        ]])

In [41]:
mean_user_rating= train_data_matrix.mean(axis=1)[:,np.newaxis]

In [42]:
mean_user_rating

array([[0.4530321 ],
       [0.09988109],
       [0.0648038 ],
       [0.04280618],
       [0.21997622],
       [0.35315101],
       [0.69381688],
       [0.09690844],
       [0.04756243],
       [0.34363853],
       [0.27705113],
       [0.10225922],
       [0.89476813],
       [0.17895363],
       [0.12485137],
       [0.25802616],
       [0.03804994],
       [0.48394768],
       [0.02853746],
       [0.06896552],
       [0.20273484],
       [0.19262782],
       [0.25267539],
       [0.11712247],
       [0.1450654 ],
       [0.14030916],
       [0.03269917],
       [0.12901308],
       [0.06123662],
       [0.07372176],
       [0.05945303],
       [0.06123662],
       [0.04280618],
       [0.03567182],
       [0.04280618],
       [0.03804994],
       [0.09750297],
       [0.2039239 ],
       [0.04221165],
       [0.05053508],
       [0.08739596],
       [0.28834721],
       [0.34661118],
       [0.25505351],
       [0.07728894],
       [0.04161712],
       [0.03567182],
       [0.115

In [43]:
rating_diff= train_data_matrix-mean_user_rating

In [44]:
rating_diff

array([[ 4.5469679 ,  2.5469679 ,  3.5469679 , ..., -0.4530321 ,
        -0.4530321 , -0.4530321 ],
       [ 3.90011891, -0.09988109, -0.09988109, ..., -0.09988109,
        -0.09988109, -0.09988109],
       [-0.0648038 , -0.0648038 , -0.0648038 , ..., -0.0648038 ,
        -0.0648038 , -0.0648038 ],
       ...,
       [ 4.960761  , -0.039239  , -0.039239  , ..., -0.039239  ,
        -0.039239  , -0.039239  ],
       [-0.16706302, -0.16706302, -0.16706302, ..., -0.16706302,
        -0.16706302, -0.16706302],
       [-0.25802616, -0.25802616, -0.25802616, ..., -0.25802616,
        -0.25802616, -0.25802616]])

In [52]:
user_pred= mean_user_rating+(user_similarity.dot(rating_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T)

In [53]:
user_pred

array([[ 1.60754164,  0.5627429 ,  0.45328176, ...,  0.30431865,
         0.30427023,  0.30412957],
       [ 1.31964714,  0.25081746,  0.10549593, ..., -0.06670901,
        -0.06521464, -0.06515514],
       [ 1.35250683,  0.21864987,  0.07582313, ..., -0.10461262,
        -0.10272656, -0.10263776],
       ...,
       [ 1.20721894,  0.18283048,  0.04411327, ..., -0.1256749 ,
        -0.12467752, -0.12475396],
       [ 1.39309262,  0.3008856 ,  0.18241367, ...,  0.00866406,
         0.00941442,  0.00962299],
       [ 1.42532389,  0.36595294,  0.25865708, ...,  0.10705407,
         0.10705937,  0.10703503]])

In [58]:
movie_pred= train_data_matrix.dot(movie_similarity)/np.array([np.abs(movie_similarity).sum(axis=1)])

In [59]:
movie_pred

array([[0.37611409, 0.39603588, 0.40805534, ..., 0.45624756, 0.44644353,
        0.44238446],
       [0.08508709, 0.09794068, 0.09484143, ..., 0.09760071, 0.10021173,
        0.09971677],
       [0.0615813 , 0.06584583, 0.06338994, ..., 0.06151931, 0.06516295,
        0.06548418],
       ...,
       [0.02737863, 0.03568359, 0.03524647, ..., 0.03927006, 0.03884056,
        0.03879776],
       [0.14135594, 0.1521122 , 0.16158738, ..., 0.1669078 , 0.16567482,
        0.16669974],
       [0.20810501, 0.21352179, 0.22782862, ..., 0.26034696, 0.25240519,
        0.25196268]])

In [60]:
from sklearn.metrics import mean_squared_error

In [61]:
from math import sqrt

In [62]:
#rmse
def rmse(pred,test):
    pred=pred[test.nonzero()].flatten()
    test=test[test.nonzero()].flatten()
    return sqrt(mean_squared_error(pred,test))

In [63]:
rmse(user_pred,train_data_matrix)

3.130210092257596

In [64]:
rmse(movie_pred,train_data_matrix)

3.4599387452998625