BluEx is a leading logistics company in India.  It's known for efficient delivery of packets to customers.  However BluEx is facing a challenge where its vandrivers are taking a suboptimal path for delivery.  This is causing delays and higher fuel cost.You as ML expert have to create a ML model using Reinforcement Learning so that efficient path is found through the program

In [1]:
import numpy as np
# R matrix
R = np.matrix([[-1,-1,0,-1,0,-1],
               [-1,-1,-1,0,-1,100],
               [-1,-1,0,0,-1,-1],
               [-1,0,-1,-1,0,-1],
               [-1,0,0,-1,-1,100],
               [-1,0,0,-1,0,100] ])
print(R)

[[ -1  -1   0  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1   0   0  -1  -1]
 [ -1   0  -1  -1   0  -1]
 [ -1   0   0  -1  -1 100]
 [ -1   0   0  -1   0 100]]


In [2]:
Q=np.matrix(np.zeros([6,6]))

In [3]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [4]:
gamma=0.8

In [5]:
initial_state=1

In [6]:
def available_actions(state):
    current_state_row = R[state,]
    av_act=np.where(current_state_row>=0)[1]
    return av_act

In [7]:
R

matrix([[ -1,  -1,   0,  -1,   0,  -1],
        [ -1,  -1,  -1,   0,  -1, 100],
        [ -1,  -1,   0,   0,  -1,  -1],
        [ -1,   0,  -1,  -1,   0,  -1],
        [ -1,   0,   0,  -1,  -1, 100],
        [ -1,   0,   0,  -1,   0, 100]])

In [8]:
available_act = available_actions(initial_state)

In [9]:
available_act

array([3, 5], dtype=int64)

In [10]:
def sample_next_action(available_actions_range):
    next_action = int(np.random.choice(available_actions_range,1))
    return next_action

In [11]:
action=sample_next_action(available_act)
print(action)

3


In [12]:
R[1,]

matrix([[ -1,  -1,  -1,   0,  -1, 100]])

In [13]:
np.max(R[1,])

100

In [14]:
def update(current_state, action, gamma):
    max_value = np.max(Q[action,])
    Q[current_state, action]=R[current_state, action]+gamma*max_value

In [15]:
update(initial_state, action, gamma)

In [16]:
for i in range(10000):
    current_state=np.random.randint(0,6)
    available_act = available_actions(current_state)
    action=sample_next_action(available_act)
    update(current_state, action, gamma)

In [17]:
current_state=2
steps=[current_state]
while current_state!=5:
    next_step_index = np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
    if next_step_index.shape[0]>1:
        next_step_index = np.random.choice(next_step_index,size=1)
    next_step_index=int(next_step_index)
    steps.append(next_step_index)
    current_state=next_step_index

In [18]:
steps

[2, 3, 1, 5]